# Generated by Django 4.1.1 on 2022-09-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='titre',
        ),
    ]
